//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("zhmdProductModel", "fk_product_type", "tbl_product_type", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(微信活动管理.Models.tbl_product_type), "tbl_product", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(微信活动管理.Models.tbl_product), true)]
[assembly: EdmRelationshipAttribute("zhmdProductModel", "fk_prodcut", "tbl_product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(微信活动管理.Models.tbl_product), "tbl_product_push_history", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(微信活动管理.Models.tbl_product_push_history), true)]

#endregion

namespace 微信活动管理.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class productEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“productEntities”部分中的连接字符串初始化新 productEntities 对象。
        /// </summary>
        public productEntities() : base("name=productEntities", "productEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 productEntities 对象。
        /// </summary>
        public productEntities(string connectionString) : base(connectionString, "productEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 productEntities 对象。
        /// </summary>
        public productEntities(EntityConnection connection) : base(connection, "productEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_product> tbl_product
        {
            get
            {
                if ((_tbl_product == null))
                {
                    _tbl_product = base.CreateObjectSet<tbl_product>("tbl_product");
                }
                return _tbl_product;
            }
        }
        private ObjectSet<tbl_product> _tbl_product;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_product_type> tbl_product_type
        {
            get
            {
                if ((_tbl_product_type == null))
                {
                    _tbl_product_type = base.CreateObjectSet<tbl_product_type>("tbl_product_type");
                }
                return _tbl_product_type;
            }
        }
        private ObjectSet<tbl_product_type> _tbl_product_type;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<printdata> printdata
        {
            get
            {
                if ((_printdata == null))
                {
                    _printdata = base.CreateObjectSet<printdata>("printdata");
                }
                return _printdata;
            }
        }
        private ObjectSet<printdata> _printdata;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_product_browse_record> tbl_product_browse_record
        {
            get
            {
                if ((_tbl_product_browse_record == null))
                {
                    _tbl_product_browse_record = base.CreateObjectSet<tbl_product_browse_record>("tbl_product_browse_record");
                }
                return _tbl_product_browse_record;
            }
        }
        private ObjectSet<tbl_product_browse_record> _tbl_product_browse_record;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_product_push_history> tbl_product_push_history
        {
            get
            {
                if ((_tbl_product_push_history == null))
                {
                    _tbl_product_push_history = base.CreateObjectSet<tbl_product_push_history>("tbl_product_push_history");
                }
                return _tbl_product_push_history;
            }
        }
        private ObjectSet<tbl_product_push_history> _tbl_product_push_history;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_wx_user> tbl_wx_user
        {
            get
            {
                if ((_tbl_wx_user == null))
                {
                    _tbl_wx_user = base.CreateObjectSet<tbl_wx_user>("tbl_wx_user");
                }
                return _tbl_wx_user;
            }
        }
        private ObjectSet<tbl_wx_user> _tbl_wx_user;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<adv_machine_product_list> adv_machine_product_list
        {
            get
            {
                if ((_adv_machine_product_list == null))
                {
                    _adv_machine_product_list = base.CreateObjectSet<adv_machine_product_list>("adv_machine_product_list");
                }
                return _adv_machine_product_list;
            }
        }
        private ObjectSet<adv_machine_product_list> _adv_machine_product_list;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<yanzhengma> yanzhengma
        {
            get
            {
                if ((_yanzhengma == null))
                {
                    _yanzhengma = base.CreateObjectSet<yanzhengma>("yanzhengma");
                }
                return _yanzhengma;
            }
        }
        private ObjectSet<yanzhengma> _yanzhengma;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_ap> tbl_ap
        {
            get
            {
                if ((_tbl_ap == null))
                {
                    _tbl_ap = base.CreateObjectSet<tbl_ap>("tbl_ap");
                }
                return _tbl_ap;
            }
        }
        private ObjectSet<tbl_ap> _tbl_ap;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tbl_product EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_product(tbl_product tbl_product)
        {
            base.AddObject("tbl_product", tbl_product);
        }
    
        /// <summary>
        /// 用于向 tbl_product_type EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_product_type(tbl_product_type tbl_product_type)
        {
            base.AddObject("tbl_product_type", tbl_product_type);
        }
    
        /// <summary>
        /// 用于向 printdata EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToprintdata(printdata printdata)
        {
            base.AddObject("printdata", printdata);
        }
    
        /// <summary>
        /// 用于向 tbl_product_browse_record EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_product_browse_record(tbl_product_browse_record tbl_product_browse_record)
        {
            base.AddObject("tbl_product_browse_record", tbl_product_browse_record);
        }
    
        /// <summary>
        /// 用于向 tbl_product_push_history EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_product_push_history(tbl_product_push_history tbl_product_push_history)
        {
            base.AddObject("tbl_product_push_history", tbl_product_push_history);
        }
    
        /// <summary>
        /// 用于向 tbl_wx_user EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_wx_user(tbl_wx_user tbl_wx_user)
        {
            base.AddObject("tbl_wx_user", tbl_wx_user);
        }
    
        /// <summary>
        /// 用于向 adv_machine_product_list EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToadv_machine_product_list(adv_machine_product_list adv_machine_product_list)
        {
            base.AddObject("adv_machine_product_list", adv_machine_product_list);
        }
    
        /// <summary>
        /// 用于向 yanzhengma EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToyanzhengma(yanzhengma yanzhengma)
        {
            base.AddObject("yanzhengma", yanzhengma);
        }
    
        /// <summary>
        /// 用于向 tbl_ap EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_ap(tbl_ap tbl_ap)
        {
            base.AddObject("tbl_ap", tbl_ap);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="adv_machine_product_list")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class adv_machine_product_list : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 adv_machine_product_list 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static adv_machine_product_list Createadv_machine_product_list(global::System.Int32 id)
        {
            adv_machine_product_list adv_machine_product_list = new adv_machine_product_list();
            adv_machine_product_list.id = id;
            return adv_machine_product_list;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_id;
        partial void Onproduct_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String machine_name
        {
            get
            {
                return _machine_name;
            }
            set
            {
                Onmachine_nameChanging(value);
                ReportPropertyChanging("machine_name");
                _machine_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("machine_name");
                Onmachine_nameChanged();
            }
        }
        private global::System.String _machine_name;
        partial void Onmachine_nameChanging(global::System.String value);
        partial void Onmachine_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> location
        {
            get
            {
                return _location;
            }
            set
            {
                OnlocationChanging(value);
                ReportPropertyChanging("location");
                _location = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("location");
                OnlocationChanged();
            }
        }
        private Nullable<global::System.Int32> _location;
        partial void OnlocationChanging(Nullable<global::System.Int32> value);
        partial void OnlocationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="printdata")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class printdata : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 printdata 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static printdata Createprintdata(global::System.Decimal id)
        {
            printdata printdata = new printdata();
            printdata.id = id;
            return printdata;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Decimal _id;
        partial void OnidChanging(global::System.Decimal value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.String _user_id;
        partial void Onuser_idChanging(global::System.String value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String machine_name
        {
            get
            {
                return _machine_name;
            }
            set
            {
                Onmachine_nameChanging(value);
                ReportPropertyChanging("machine_name");
                _machine_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("machine_name");
                Onmachine_nameChanged();
            }
        }
        private global::System.String _machine_name;
        partial void Onmachine_nameChanging(global::System.String value);
        partial void Onmachine_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> print_time
        {
            get
            {
                return _print_time;
            }
            set
            {
                Onprint_timeChanging(value);
                ReportPropertyChanging("print_time");
                _print_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("print_time");
                Onprint_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _print_time;
        partial void Onprint_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onprint_timeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="tbl_ap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ap : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_ap 对象。
        /// </summary>
        /// <param name="ap_mac">ap_mac 属性的初始值。</param>
        public static tbl_ap Createtbl_ap(global::System.String ap_mac)
        {
            tbl_ap tbl_ap = new tbl_ap();
            tbl_ap.ap_mac = ap_mac;
            return tbl_ap;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ap_mac
        {
            get
            {
                return _ap_mac;
            }
            set
            {
                if (_ap_mac != value)
                {
                    Onap_macChanging(value);
                    ReportPropertyChanging("ap_mac");
                    _ap_mac = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ap_mac");
                    Onap_macChanged();
                }
            }
        }
        private global::System.String _ap_mac;
        partial void Onap_macChanging(global::System.String value);
        partial void Onap_macChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> store_id
        {
            get
            {
                return _store_id;
            }
            set
            {
                Onstore_idChanging(value);
                ReportPropertyChanging("store_id");
                _store_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("store_id");
                Onstore_idChanged();
            }
        }
        private Nullable<global::System.Int32> _store_id;
        partial void Onstore_idChanging(Nullable<global::System.Int32> value);
        partial void Onstore_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ap_groupname
        {
            get
            {
                return _ap_groupname;
            }
            set
            {
                Onap_groupnameChanging(value);
                ReportPropertyChanging("ap_groupname");
                _ap_groupname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ap_groupname");
                Onap_groupnameChanged();
            }
        }
        private global::System.String _ap_groupname;
        partial void Onap_groupnameChanging(global::System.String value);
        partial void Onap_groupnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="tbl_product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_product : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_product 对象。
        /// </summary>
        /// <param name="product_id">product_id 属性的初始值。</param>
        /// <param name="product_name">product_name 属性的初始值。</param>
        /// <param name="description">description 属性的初始值。</param>
        /// <param name="create_time">create_time 属性的初始值。</param>
        /// <param name="push_level">push_level 属性的初始值。</param>
        public static tbl_product Createtbl_product(global::System.Int32 product_id, global::System.String product_name, global::System.String description, global::System.DateTime create_time, global::System.SByte push_level)
        {
            tbl_product tbl_product = new tbl_product();
            tbl_product.product_id = product_id;
            tbl_product.product_name = product_name;
            tbl_product.description = description;
            tbl_product.create_time = create_time;
            tbl_product.push_level = push_level;
            return tbl_product;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.Int32 _product_id;
        partial void Onproduct_idChanging(global::System.Int32 value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content_url
        {
            get
            {
                return _content_url;
            }
            set
            {
                Oncontent_urlChanging(value);
                ReportPropertyChanging("content_url");
                _content_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content_url");
                Oncontent_urlChanged();
            }
        }
        private global::System.String _content_url;
        partial void Oncontent_urlChanging(global::System.String value);
        partial void Oncontent_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> product_type
        {
            get
            {
                return _product_type;
            }
            set
            {
                Onproduct_typeChanging(value);
                ReportPropertyChanging("product_type");
                _product_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_type");
                Onproduct_typeChanged();
            }
        }
        private Nullable<global::System.SByte> _product_type;
        partial void Onproduct_typeChanging(Nullable<global::System.SByte> value);
        partial void Onproduct_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime create_time
        {
            get
            {
                return _create_time;
            }
            set
            {
                Oncreate_timeChanging(value);
                ReportPropertyChanging("create_time");
                _create_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("create_time");
                Oncreate_timeChanged();
            }
        }
        private global::System.DateTime _create_time;
        partial void Oncreate_timeChanging(global::System.DateTime value);
        partial void Oncreate_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> expire_time
        {
            get
            {
                return _expire_time;
            }
            set
            {
                Onexpire_timeChanging(value);
                ReportPropertyChanging("expire_time");
                _expire_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("expire_time");
                Onexpire_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _expire_time;
        partial void Onexpire_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onexpire_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte push_level
        {
            get
            {
                return _push_level;
            }
            set
            {
                Onpush_levelChanging(value);
                ReportPropertyChanging("push_level");
                _push_level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("push_level");
                Onpush_levelChanged();
            }
        }
        private global::System.SByte _push_level;
        partial void Onpush_levelChanging(global::System.SByte value);
        partial void Onpush_levelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pic_url
        {
            get
            {
                return _pic_url;
            }
            set
            {
                Onpic_urlChanging(value);
                ReportPropertyChanging("pic_url");
                _pic_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pic_url");
                Onpic_urlChanged();
            }
        }
        private global::System.String _pic_url;
        partial void Onpic_urlChanging(global::System.String value);
        partial void Onpic_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String short_url
        {
            get
            {
                return _short_url;
            }
            set
            {
                Onshort_urlChanging(value);
                ReportPropertyChanging("short_url");
                _short_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("short_url");
                Onshort_urlChanged();
            }
        }
        private global::System.String _short_url;
        partial void Onshort_urlChanging(global::System.String value);
        partial void Onshort_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ticket_url
        {
            get
            {
                return _ticket_url;
            }
            set
            {
                Onticket_urlChanging(value);
                ReportPropertyChanging("ticket_url");
                _ticket_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ticket_url");
                Onticket_urlChanged();
            }
        }
        private global::System.String _ticket_url;
        partial void Onticket_urlChanging(global::System.String value);
        partial void Onticket_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> product_status
        {
            get
            {
                return _product_status;
            }
            set
            {
                Onproduct_statusChanging(value);
                ReportPropertyChanging("product_status");
                _product_status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_status");
                Onproduct_statusChanged();
            }
        }
        private Nullable<global::System.Boolean> _product_status;
        partial void Onproduct_statusChanging(Nullable<global::System.Boolean> value);
        partial void Onproduct_statusChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zhmdProductModel", "fk_product_type", "tbl_product_type")]
        public tbl_product_type tbl_product_type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_product_type>("zhmdProductModel.fk_product_type", "tbl_product_type").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_product_type>("zhmdProductModel.fk_product_type", "tbl_product_type").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_product_type> tbl_product_typeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_product_type>("zhmdProductModel.fk_product_type", "tbl_product_type");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_product_type>("zhmdProductModel.fk_product_type", "tbl_product_type", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zhmdProductModel", "fk_prodcut", "tbl_product_push_history")]
        public EntityCollection<tbl_product_push_history> tbl_product_push_history
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_product_push_history>("zhmdProductModel.fk_prodcut", "tbl_product_push_history");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_product_push_history>("zhmdProductModel.fk_prodcut", "tbl_product_push_history", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="tbl_product_browse_record")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_product_browse_record : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_product_browse_record 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static tbl_product_browse_record Createtbl_product_browse_record(global::System.Int32 id)
        {
            tbl_product_browse_record tbl_product_browse_record = new tbl_product_browse_record();
            tbl_product_browse_record.id = id;
            return tbl_product_browse_record;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.String _user_id;
        partial void Onuser_idChanging(global::System.String value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_id;
        partial void Onproduct_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _datetime;
        partial void OndatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OndatetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> browse_type
        {
            get
            {
                return _browse_type;
            }
            set
            {
                Onbrowse_typeChanging(value);
                ReportPropertyChanging("browse_type");
                _browse_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("browse_type");
                Onbrowse_typeChanged();
            }
        }
        private Nullable<global::System.SByte> _browse_type;
        partial void Onbrowse_typeChanging(Nullable<global::System.SByte> value);
        partial void Onbrowse_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String machine_name
        {
            get
            {
                return _machine_name;
            }
            set
            {
                Onmachine_nameChanging(value);
                ReportPropertyChanging("machine_name");
                _machine_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("machine_name");
                Onmachine_nameChanged();
            }
        }
        private global::System.String _machine_name;
        partial void Onmachine_nameChanging(global::System.String value);
        partial void Onmachine_nameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="tbl_product_push_history")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_product_push_history : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_product_push_history 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static tbl_product_push_history Createtbl_product_push_history(global::System.Int32 id)
        {
            tbl_product_push_history tbl_product_push_history = new tbl_product_push_history();
            tbl_product_push_history.id = id;
            return tbl_product_push_history;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> store_id
        {
            get
            {
                return _store_id;
            }
            set
            {
                Onstore_idChanging(value);
                ReportPropertyChanging("store_id");
                _store_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("store_id");
                Onstore_idChanged();
            }
        }
        private Nullable<global::System.Int32> _store_id;
        partial void Onstore_idChanging(Nullable<global::System.Int32> value);
        partial void Onstore_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_id;
        partial void Onproduct_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String openid
        {
            get
            {
                return _openid;
            }
            set
            {
                OnopenidChanging(value);
                ReportPropertyChanging("openid");
                _openid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("openid");
                OnopenidChanged();
            }
        }
        private global::System.String _openid;
        partial void OnopenidChanging(global::System.String value);
        partial void OnopenidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mobile
        {
            get
            {
                return _mobile;
            }
            set
            {
                OnmobileChanging(value);
                ReportPropertyChanging("mobile");
                _mobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mobile");
                OnmobileChanged();
            }
        }
        private global::System.String _mobile;
        partial void OnmobileChanging(global::System.String value);
        partial void OnmobileChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String push_type
        {
            get
            {
                return _push_type;
            }
            set
            {
                Onpush_typeChanging(value);
                ReportPropertyChanging("push_type");
                _push_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("push_type");
                Onpush_typeChanged();
            }
        }
        private global::System.String _push_type;
        partial void Onpush_typeChanging(global::System.String value);
        partial void Onpush_typeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> push_time
        {
            get
            {
                return _push_time;
            }
            set
            {
                Onpush_timeChanging(value);
                ReportPropertyChanging("push_time");
                _push_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("push_time");
                Onpush_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _push_time;
        partial void Onpush_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onpush_timeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zhmdProductModel", "fk_prodcut", "tbl_product")]
        public tbl_product tbl_product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_product>("zhmdProductModel.fk_prodcut", "tbl_product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_product>("zhmdProductModel.fk_prodcut", "tbl_product").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_product> tbl_productReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_product>("zhmdProductModel.fk_prodcut", "tbl_product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_product>("zhmdProductModel.fk_prodcut", "tbl_product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="tbl_product_type")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_product_type : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_product_type 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static tbl_product_type Createtbl_product_type(global::System.SByte id)
        {
            tbl_product_type tbl_product_type = new tbl_product_type();
            tbl_product_type.id = id;
            return tbl_product_type;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.SByte _id;
        partial void OnidChanging(global::System.SByte value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type_pic_url
        {
            get
            {
                return _type_pic_url;
            }
            set
            {
                Ontype_pic_urlChanging(value);
                ReportPropertyChanging("type_pic_url");
                _type_pic_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type_pic_url");
                Ontype_pic_urlChanged();
            }
        }
        private global::System.String _type_pic_url;
        partial void Ontype_pic_urlChanging(global::System.String value);
        partial void Ontype_pic_urlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> parent_id
        {
            get
            {
                return _parent_id;
            }
            set
            {
                Onparent_idChanging(value);
                ReportPropertyChanging("parent_id");
                _parent_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parent_id");
                Onparent_idChanged();
            }
        }
        private Nullable<global::System.SByte> _parent_id;
        partial void Onparent_idChanging(Nullable<global::System.SByte> value);
        partial void Onparent_idChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("zhmdProductModel", "fk_product_type", "tbl_product")]
        public EntityCollection<tbl_product> tbl_product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_product>("zhmdProductModel.fk_product_type", "tbl_product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_product>("zhmdProductModel.fk_product_type", "tbl_product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="tbl_wx_user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_wx_user : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_wx_user 对象。
        /// </summary>
        /// <param name="openid">openid 属性的初始值。</param>
        public static tbl_wx_user Createtbl_wx_user(global::System.String openid)
        {
            tbl_wx_user tbl_wx_user = new tbl_wx_user();
            tbl_wx_user.openid = openid;
            return tbl_wx_user;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String public_number
        {
            get
            {
                return _public_number;
            }
            set
            {
                Onpublic_numberChanging(value);
                ReportPropertyChanging("public_number");
                _public_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("public_number");
                Onpublic_numberChanged();
            }
        }
        private global::System.String _public_number;
        partial void Onpublic_numberChanging(global::System.String value);
        partial void Onpublic_numberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String openid
        {
            get
            {
                return _openid;
            }
            set
            {
                if (_openid != value)
                {
                    OnopenidChanging(value);
                    ReportPropertyChanging("openid");
                    _openid = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("openid");
                    OnopenidChanged();
                }
            }
        }
        private global::System.String _openid;
        partial void OnopenidChanging(global::System.String value);
        partial void OnopenidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nickname
        {
            get
            {
                return _nickname;
            }
            set
            {
                OnnicknameChanging(value);
                ReportPropertyChanging("nickname");
                _nickname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nickname");
                OnnicknameChanged();
            }
        }
        private global::System.String _nickname;
        partial void OnnicknameChanging(global::System.String value);
        partial void OnnicknameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remark
        {
            get
            {
                return _remark;
            }
            set
            {
                OnremarkChanging(value);
                ReportPropertyChanging("remark");
                _remark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remark");
                OnremarkChanged();
            }
        }
        private global::System.String _remark;
        partial void OnremarkChanging(global::System.String value);
        partial void OnremarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private Nullable<global::System.Int32> _sex;
        partial void OnsexChanging(Nullable<global::System.Int32> value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> subscribe_time
        {
            get
            {
                return _subscribe_time;
            }
            set
            {
                Onsubscribe_timeChanging(value);
                ReportPropertyChanging("subscribe_time");
                _subscribe_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subscribe_time");
                Onsubscribe_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _subscribe_time;
        partial void Onsubscribe_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onsubscribe_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> subscribe
        {
            get
            {
                return _subscribe;
            }
            set
            {
                OnsubscribeChanging(value);
                ReportPropertyChanging("subscribe");
                _subscribe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("subscribe");
                OnsubscribeChanged();
            }
        }
        private Nullable<global::System.Int32> _subscribe;
        partial void OnsubscribeChanging(Nullable<global::System.Int32> value);
        partial void OnsubscribeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> update_time
        {
            get
            {
                return _update_time;
            }
            set
            {
                Onupdate_timeChanging(value);
                ReportPropertyChanging("update_time");
                _update_time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("update_time");
                Onupdate_timeChanged();
            }
        }
        private Nullable<global::System.DateTime> _update_time;
        partial void Onupdate_timeChanging(Nullable<global::System.DateTime> value);
        partial void Onupdate_timeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String headimgurl
        {
            get
            {
                return _headimgurl;
            }
            set
            {
                OnheadimgurlChanging(value);
                ReportPropertyChanging("headimgurl");
                _headimgurl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("headimgurl");
                OnheadimgurlChanged();
            }
        }
        private global::System.String _headimgurl;
        partial void OnheadimgurlChanging(global::System.String value);
        partial void OnheadimgurlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="zhmdProductModel", Name="yanzhengma")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class yanzhengma : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 yanzhengma 对象。
        /// </summary>
        /// <param name="machineName">MachineName 属性的初始值。</param>
        public static yanzhengma Createyanzhengma(global::System.String machineName)
        {
            yanzhengma yanzhengma = new yanzhengma();
            yanzhengma.MachineName = machineName;
            return yanzhengma;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MachineName
        {
            get
            {
                return _MachineName;
            }
            set
            {
                if (_MachineName != value)
                {
                    OnMachineNameChanging(value);
                    ReportPropertyChanging("MachineName");
                    _MachineName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MachineName");
                    OnMachineNameChanged();
                }
            }
        }
        private global::System.String _MachineName;
        partial void OnMachineNameChanging(global::System.String value);
        partial void OnMachineNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String code
        {
            get
            {
                return _code;
            }
            set
            {
                OncodeChanging(value);
                ReportPropertyChanging("code");
                _code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("code");
                OncodeChanged();
            }
        }
        private global::System.String _code;
        partial void OncodeChanging(global::System.String value);
        partial void OncodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NickName
        {
            get
            {
                return _NickName;
            }
            set
            {
                OnNickNameChanging(value);
                ReportPropertyChanging("NickName");
                _NickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NickName");
                OnNickNameChanged();
            }
        }
        private global::System.String _NickName;
        partial void OnNickNameChanging(global::System.String value);
        partial void OnNickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                OnLocationNameChanging(value);
                ReportPropertyChanging("LocationName");
                _LocationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LocationName");
                OnLocationNameChanged();
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();

        #endregion
    
    }

    #endregion
    
}
